export const usersArray = [
  {
    id: 1,
    name: "Leslie Maya",
    email: "leslie@gmail.com",
    location: "Los Angeles, CA",
    joined: "October 2, 2010",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 2,
    name: "Josie Deck",
    email: "josie@gmail.com",
    location: "Cheyenne, WY",
    joined: "October 3, 2011",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Alex Pfeiffer",
    email: "alex@gmail.com",
    location: "Cheyenne, WY",
    joined: "May 20, 2015",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Mike Dean",
    email: "mike@gmail.com",
    location: "Syracuse, NY",
    joined: "July 14, 2015",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    name: "Mateus Cunha",
    email: "cunha@gmail.com",
    location: "Luanda, AN",
    joined: "October, 2016",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Nzola Uemo",
    email: "nzola@gmail.com",
    location: "Lagos, NG",
    joined: "June 5, 2016",
    role: "Viewer",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Antony Mack",
    email: "mack@gmail.com",
    location: "London, ENG",
    joined: "June 15, 2015",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "André da Silva",
    email: "andré@gmail.com",
    location: "São Paulo, BR",
    joined: "March 13, 2018",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Jorge Ferreira",
    email: "jorge12@gmail.com",
    location: "Huambo, Angola",
    joined: "March 14, 2018",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 20,
    name: "Jorge Ferreira",
    email: "jorgee3123@gmail.com",
    location: "Huambo, Angola",
    joined: "March 14, 2018",
    role: "Viewer",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Leslie",
    email: "leslie412@gmail.com",
    location: "Los Angeles, CA",
    joined: "October 2, 2010",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 11,
    name: " Deck",
    email: "josie412@gmail.com",
    location: "Cheyenne, WY",
    joined: "October 3, 2011",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 12,
    name: "Alex",
    email: "ale512x@gmail.com",
    location: "Cheyenne, WY",
    joined: "May 20, 2015",
    role: "Admin",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 13,
    name: "Dean",
    email: "mi51245ke@gmail.com",
    location: "Syracuse, NY",
    joined: "July 14, 2015",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 14,
    name: "Mateus",
    email: "cun52151ha@gmail.com",
    location: "Luanda, AN",
    joined: "October, 2016",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 15,
    name: "Uemo",
    email: "nz51241ola@gmail.com",
    location: "Lagos, NG",
    joined: "June 5, 2016",
    role: "Viewer",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 16,
    name: "Antony Mack",
    email: "ma5213ck@gmail.com",
    location: "London, ENG",
    joined: "June 15, 2015",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 17,
    name: "André da Silva",
    email: "and512412ré@gmail.com",
    location: "São Paulo, BR",
    joined: "March 13, 2018",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 18,
    name: "Jorge Ferreira",
    email: "jor61232ge@gmail.com",
    location: "Huambo, Angola",
    joined: "March 14, 2018",
    role: "Contributor",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 19,
    name: " Ferreira",
    email: "jor6123gee@gmail.com",
    location: "Huambo, Angola",
    joined: "March 14, 2018",
    role: "Viewer",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
];
